In [20]:
import kaggle
!kaggle datasets download mohammadtalib786/retail-sales-dataset -f retail_sales_dataset.csv
!kaggle datasets download nishthakapoor17/retail -f Customer.csv

Dataset URL: https://www.kaggle.com/datasets/mohammadtalib786/retail-sales-dataset
License(s): CC0-1.0
retail_sales_dataset.csv: Skipping, found more recently modified local copy (use --force to force download)
Dataset URL: https://www.kaggle.com/datasets/nishthakapoor17/retail
License(s): unknown
Customer.csv: Skipping, found more recently modified local copy (use --force to force download)

In [14]:
# extracting file from zip file
import zipfile
zip_ref = zipfile.ZipFile('Transactions.csv.zip')
zip_ref.extractall()
zip_ref.close()

In [21]:
import pandas as pd
dft =pd.read_csv('Transactions.csv')
dft.head(20)

,transaction_id,cust_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type
0,80712190438,270351,28-02-2014,1,1,-5,-772,405.300,-4265.300,e-Shop
1,29258453508,270384,27-02-2014,5,3,-5,-1497,785.925,-8270.925,e-Shop
2,51750724947,273420,24-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop
3,93274880719,271509,24-02-2014,11,6,-3,-1363,429.345,-4518.345,e-Shop
4,51750724947,273420,23-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop
5,97439039119,272357,23-02-2014,8,3,-2,-824,173.040,-1821.040,TeleShop
6,45649838090,273667,22-02-2014,11,6,-1,-1450,152.250,-1602.250,e-Shop
7,22643667930,271489,22-02-2014,12,6,-1,-1225,128.625,-1353.625,TeleShop
8,79792372943,275108,22-02-2014,3,1,-3,-908,286.020,-3010.020,MBR
9,50076728598,269014,21-02-2014,8,3,-4,-581,244.020,-2568.020,e-Shop
10,29258453508,270384,20-02-2014,5,3,5,1497,785.925,8270.925,e-Shop
11,25455265351,267750,20-02-2014,12,6,3,1360,428.400,4508.400,e-Shop
12,1571002198,275023,20-02-2014,6,5,4,587,246.540,2594.540,e-Shop
13,43134751727,268487,20-02-2014,3,2,-1,-611,64.155,-675.155,e-Shop
14,36554696014,269345,20-02-2014,3,5,3,1253,394.695,4153.695,e-Shop
15,56814940239,268799,20-02-2014,7,5,5,368,193.200,2033.200,e-Shop
16,54295803788,270787,20-02-2014,12,5,5,584,306.600,3226.600,e-Shop
17,25963520987,274829,20-02-2014,4,4,3,502,158.130,1664.130,Flagship store
18,17183929085,266863,20-02-2014,1,2,1,1359,142.695,1501.695,TeleShop
19,44783317894,269452,20-02-2014,3,1,3,825,259.875,2734.875,TeleShop

In [23]:
dfc=pd.read_csv('Customer.csv')
dfc.head(20)

    customer_Id         DOB Gender  city_code
0        268408  02-01-1970      M        4.0
1        269696  07-01-1970      F        8.0
2        268159  08-01-1970      F        8.0
3        270181  10-01-1970      F        2.0
4        268073  11-01-1970      M        1.0
5        273216  15-01-1970      F        5.0
6        266929  15-01-1970      M        8.0
7        275152  16-01-1970      M        4.0
8        275034  18-01-1970      F        4.0
9        273966  21-01-1970      M        8.0
10       270829  22-01-1970      F        8.0
11       266997  23-01-1970      M        9.0
12       272455  25-01-1970      M        7.0
13       274593  26-01-1970      M       10.0
14       273391  29-01-1970      F        2.0
15       267657  29-01-1970      F        7.0
16       271344  29-01-1970      F        5.0
17       268275  01-02-1970      F        7.0
18       274630  01-02-1970      M        4.0
19       273541  01-02-1970      M        4.0

In [24]:
dfp=pd.read_csv('prod_cat_info.csv')
dfp.head(20)

    prod_cat_code          prod_cat  prod_sub_cat_code          prod_subcat
0               1          Clothing                  4                 Mens
1               1          Clothing                  1                Women
2               1          Clothing                  3                 Kids
3               2          Footwear                  1                 Mens
4               2          Footwear                  3                Women
5               2          Footwear                  4                 Kids
6               3       Electronics                  4              Mobiles
7               3       Electronics                  5            Computers
8               3       Electronics                  8  Personal Appliances
9               3       Electronics                  9              Cameras
10              3       Electronics                 10      Audio and video
11              4              Bags                  1                 Mens
12              4              Bags                  4                Women
13              5             Books                  7              Fiction
14              5             Books                 12             Academic
15              5             Books                 10          Non-Fiction
16              5             Books                 11             Children
17              5             Books                  3               Comics
18              5             Books                  6                  DIY
19              6  Home and kitchen                  2           Furnishing

In [30]:
dfc.rename(columns={'Gender':'gender','DOB':'dob'})
dfc.columns=dfc.columns.str.lower()
dfc.columns
dfc.columns.str.replace(' ','_')

Index(['customer_id', 'dob', 'gender', 'city_code'], dtype='str')

In [31]:
dfc.head(10)

   customer_id         dob gender  city_code
0       268408  02-01-1970      M        4.0
1       269696  07-01-1970      F        8.0
2       268159  08-01-1970      F        8.0
3       270181  10-01-1970      F        2.0
4       268073  11-01-1970      M        1.0
5       273216  15-01-1970      F        5.0
6       266929  15-01-1970      M        8.0
7       275152  16-01-1970      M        4.0
8       275034  18-01-1970      F        4.0
9       273966  21-01-1970      M        8.0